name:                hmgit
version:             1.0.0
github:              "falgon/hmgit"
license:             BSD3
author:              "Roki"
maintainer:          "falgon53@yahoo.co.jp"
copyright:           "2021 Roki"
extra-source-files:
- README.md
- ChangeLog.md
synopsis:            The subset of awesome content tracker Git
category:            Git
description:         Please see the README on GitHub at <https://github.com/falgon/hmgit#readme>
dependencies:
- base >= 4.7 && < 5
- directory
- filepath
- bytestring
- cryptohash
- utf8-string
- zlib
- safe-exceptions
- transformers
- megaparsec
- mtl
- monad-loops
- extra
- optparse-applicative
- binary
- natural-transformation
- Glob
- containers
- path >= 0.8.0
- path-io
- regex-posix
- Diff
- pretty
- unix
- file-embed
- template-haskell
- time
- mono-traversable

library:
  source-dirs: src

executables:
  hmgit:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -O2
    dependencies:
    - hmgit
    - gitrev
    other-modules: Paths_hmgit

tests:
  hmgit-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    dependencies:
    - hmgit
    - HUnit
    - hspec
    - hspec-core
    - hspec-contrib
