name:                hmgit
version:             0.1.0.0
github:              "falgon/hmgit"
license:             BSD3
author:              "Roki"
maintainer:          "example@example.com"
copyright:           "2021 Roki"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hmgit#readme>

dependencies:
- base >= 4.7 && < 5
- directory
- filepath
- bytestring
- cryptohash
- utf8-string
- zlib
- safe-exceptions
- transformers
- megaparsec
- mtl
- monad-loops
- extra
- optparse-applicative
- binary
- natural-transformation
- Glob
- containers
- path >= 0.8.0
- path-io
- regex-posix

library:
  source-dirs: src

executables:
  hmgit:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -O2
    dependencies:
    - hmgit
    when:
    - condition: false
      other-modules: Paths_hmgit

tests:
  hmgit-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hmgit
    - HUnit
    - hspec
    - hspec-core
    - hspec-contrib
